spring:
  application:
    name: backend
  elasticsearch:
    uris: ${ES_URL:http://localhost:9200}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/knewit}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:blackmamba}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect