# ==========================================
# APPLICATION
# ==========================================
spring.application.name=knewit-backend

server.port=8080

# ==========================================
# DATABASE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/knewit
spring.datasource.username=postgres
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# LOGGING
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE



spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

cloudinary.cloud-name=duvpyrpla
cloudinary.api-key=389639423134836
cloudinary.api-secret=RJ3qzrQhRYx9X-yDIuujsqoa7A8

