spring:
  application:
    name: backend
  elasticsearch:
    uris: ${ES_URL}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}
    ssl:
      verification-mode: none
  mail:
    host: ${EMAIL_APP_HOST}
    port: ${EMAIL_APP_PORT}
    username: ${EMAIL_APP_USERNAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/knewit}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  app:
    websocket:
      endpoint-path: /ws
      broker-prefix: /app
      topic-prefix: /topic
      queue-prefix: /queue
      allowed-origins: http://localhost:5173
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${COUDINARY_API_SECRET}

secret-key: ${JWT_SECRET_KEY}
frontend-url: http://localhost:8080/api/v1/auth
auth-url: http://localhost:8080/api/v1/auth